<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv\SourceChapterRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>srv.SourceChapterRequest.ChapterSource</code>
 */
class ChapterSource extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string chapterLink = 1;</code>
     */
    private $chapterLink = '';
    /**
     * Generated from protobuf field <code>string source = 2;</code>
     */
    private $source = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $chapterLink
     *     @type string $source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\BookService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string chapterLink = 1;</code>
     * @return string
     */
    public function getChapterLink()
    {
        return $this->chapterLink;
    }

    /**
     * Generated from protobuf field <code>string chapterLink = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setChapterLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->chapterLink = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source = 2;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>string source = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ChapterSource::class, \Srv\SourceChapterRequest_ChapterSource::class);

