<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/ParserService.protoc

namespace GPBMetadata\Protoc;

class ParserService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad020a1b70726f746f632f506172736572536572766963652e70726f74" .
            "6f631203737276222e0a0e4368617074657252657175657374120c0a046c" .
            "696e6b180120012809120e0a06736f757263651802200128092280010a0f" .
            "43686170746572526573706f6e7365122e0a086368617074657273180120" .
            "03280b321c2e7372762e43686170746572526573706f6e73652e43686170" .
            "7465721a3d0a0743686170746572120d0a057469746c6518012001280912" .
            "0d0a05696e64657818022001280512140a0c636f6e74656e74734c696e6b" .
            "180320012809324e0a0d50617273657253657276696365123d0a0e506172" .
            "736572436861707465727312132e7372762e436861707465725265717565" .
            "73741a142e7372762e43686170746572526573706f6e7365220062067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

