<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/ParserService.protoc

namespace GPBMetadata\Protoc;

class ParserService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9d020a1b70726f746f632f506172736572536572766963652e70726f74" .
            "6f631203737276221e0a0e4368617074657252657175657374120c0a046c" .
            "696e6b1801200128092280010a0f43686170746572526573706f6e736512" .
            "2e0a08636861707465727318012003280b321c2e7372762e436861707465" .
            "72526573706f6e73652e436861707465721a3d0a0743686170746572120d" .
            "0a057469746c65180120012809120d0a05696e6465781802200128051214" .
            "0a0c636f6e74656e74734c696e6b180320012809324e0a0d506172736572" .
            "53657276696365123d0a0e506172736572436861707465727312132e7372" .
            "762e43686170746572526571756573741a142e7372762e43686170746572" .
            "526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

