<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv\SearchBookResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>srv.SearchBookResponse.Book</code>
 */
class Book extends \Google\Protobuf\Internal\Message
{
    /**
     *书籍名称
     *
     * Generated from protobuf field <code>string title = 1;</code>
     */
    private $title = '';
    /**
     *作者
     *
     * Generated from protobuf field <code>string author = 2;</code>
     */
    private $author = '';
    /**
     *封面图
     *
     * Generated from protobuf field <code>string cover = 3;</code>
     */
    private $cover = '';
    /**
     *状态
     *
     * Generated from protobuf field <code>string status = 4;</code>
     */
    private $status = '';
    /**
     *书籍详情
     *
     * Generated from protobuf field <code>string detail = 5;</code>
     */
    private $detail = '';
    /**
     *章节链接
     *
     * Generated from protobuf field <code>string link = 6;</code>
     */
    private $link = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *          书籍名称
     *     @type string $author
     *          作者
     *     @type string $cover
     *          封面图
     *     @type string $status
     *          状态
     *     @type string $detail
     *          书籍详情
     *     @type string $link
     *          章节链接
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\BookService::initOnce();
        parent::__construct($data);
    }

    /**
     *书籍名称
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     *书籍名称
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     *作者
     *
     * Generated from protobuf field <code>string author = 2;</code>
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     *作者
     *
     * Generated from protobuf field <code>string author = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkString($var, True);
        $this->author = $var;

        return $this;
    }

    /**
     *封面图
     *
     * Generated from protobuf field <code>string cover = 3;</code>
     * @return string
     */
    public function getCover()
    {
        return $this->cover;
    }

    /**
     *封面图
     *
     * Generated from protobuf field <code>string cover = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCover($var)
    {
        GPBUtil::checkString($var, True);
        $this->cover = $var;

        return $this;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>string status = 4;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>string status = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     *书籍详情
     *
     * Generated from protobuf field <code>string detail = 5;</code>
     * @return string
     */
    public function getDetail()
    {
        return $this->detail;
    }

    /**
     *书籍详情
     *
     * Generated from protobuf field <code>string detail = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->detail = $var;

        return $this;
    }

    /**
     *章节链接
     *
     * Generated from protobuf field <code>string link = 6;</code>
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     *章节链接
     *
     * Generated from protobuf field <code>string link = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->link = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Book::class, \Srv\SearchBookResponse_Book::class);

