<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *获取书籍信息
 *
 * Generated from protobuf message <code>srv.BookRequest</code>
 */
class BookRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *
     * Generated from protobuf field <code>string link = 1;</code>
     */
    private $link = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $link
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\BookService::initOnce();
        parent::__construct($data);
    }

    /**
     *
     * Generated from protobuf field <code>string link = 1;</code>
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     *
     * Generated from protobuf field <code>string link = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->link = $var;

        return $this;
    }

}

