<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

if (false) {
    /**
     * This class is deprecated. Use Srv\BookResponse\Book instead.
     * @deprecated
     */
    class BookResponse_Book {}
}
class_exists(BookResponse\Book::class);
@trigger_error('Srv\BookResponse_Book is deprecated and will be removed in the next major release. Use Srv\BookResponse\Book instead', E_USER_DEPRECATED);

