<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>srv.BookResponse</code>
 */
class BookResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *
     * Generated from protobuf field <code>.srv.BookResponse.Book book = 1;</code>
     */
    private $book = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Srv\BookResponse\Book $book
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\BookService::initOnce();
        parent::__construct($data);
    }

    /**
     *
     * Generated from protobuf field <code>.srv.BookResponse.Book book = 1;</code>
     * @return \Srv\BookResponse\Book
     */
    public function getBook()
    {
        return $this->book;
    }

    /**
     *
     * Generated from protobuf field <code>.srv.BookResponse.Book book = 1;</code>
     * @param \Srv\BookResponse\Book $var
     * @return $this
     */
    public function setBook($var)
    {
        GPBUtil::checkMessage($var, \Srv\BookResponse_Book::class);
        $this->book = $var;

        return $this;
    }

}

