<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/ParserService.protoc

namespace Srv;

if (false) {
    /**
     * This class is deprecated. Use Srv\ChapterResponse\Chapter instead.
     * @deprecated
     */
    class ChapterResponse_Chapter {}
}
class_exists(ChapterResponse\Chapter::class);
@trigger_error('Srv\ChapterResponse_Chapter is deprecated and will be removed in the next major release. Use Srv\ChapterResponse\Chapter instead', E_USER_DEPRECATED);

