<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/ParserService.protoc

namespace Srv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>srv.ChapterContentRequest</code>
 */
class ChapterContentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *链接
     *
     * Generated from protobuf field <code>string link = 1;</code>
     */
    private $link = '';
    /**
     *源站
     *
     * Generated from protobuf field <code>string source = 2;</code>
     */
    private $source = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $link
     *          链接
     *     @type string $source
     *          源站
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\ParserService::initOnce();
        parent::__construct($data);
    }

    /**
     *链接
     *
     * Generated from protobuf field <code>string link = 1;</code>
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     *链接
     *
     * Generated from protobuf field <code>string link = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->link = $var;

        return $this;
    }

    /**
     *源站
     *
     * Generated from protobuf field <code>string source = 2;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     *源站
     *
     * Generated from protobuf field <code>string source = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

}

