<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *搜索书籍服务
 *
 * Generated from protobuf message <code>srv.SearchBookRequest</code>
 */
class SearchBookRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string keyword = 1;</code>
     */
    private $keyword = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keyword
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\BookService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string keyword = 1;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     * Generated from protobuf field <code>string keyword = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

}

