<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>srv.SearchBookResponse</code>
 */
class SearchBookResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *
     * Generated from protobuf field <code>repeated .srv.SearchBookResponse.Book books = 1;</code>
     */
    private $books;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Srv\SearchBookResponse\Book[]|\Google\Protobuf\Internal\RepeatedField $books
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\BookService::initOnce();
        parent::__construct($data);
    }

    /**
     *
     * Generated from protobuf field <code>repeated .srv.SearchBookResponse.Book books = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBooks()
    {
        return $this->books;
    }

    /**
     *
     * Generated from protobuf field <code>repeated .srv.SearchBookResponse.Book books = 1;</code>
     * @param \Srv\SearchBookResponse\Book[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBooks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Srv\SearchBookResponse\Book::class);
        $this->books = $arr;

        return $this;
    }

}

