<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

if (false) {
    /**
     * This class is deprecated. Use Srv\SearchBookResponse\Book instead.
     * @deprecated
     */
    class SearchBookResponse_Book {}
}
class_exists(SearchBookResponse\Book::class);
@trigger_error('Srv\SearchBookResponse_Book is deprecated and will be removed in the next major release. Use Srv\SearchBookResponse\Book instead', E_USER_DEPRECATED);

