<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>srv.SourceChapterResponse</code>
 */
class SourceChapterResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .srv.SourceChapterResponse.ChapterInfo chapterInfo = 1;</code>
     */
    private $chapterInfo;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Srv\SourceChapterResponse\ChapterInfo[]|\Google\Protobuf\Internal\RepeatedField $chapterInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\BookService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .srv.SourceChapterResponse.ChapterInfo chapterInfo = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChapterInfo()
    {
        return $this->chapterInfo;
    }

    /**
     * Generated from protobuf field <code>repeated .srv.SourceChapterResponse.ChapterInfo chapterInfo = 1;</code>
     * @param \Srv\SourceChapterResponse\ChapterInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChapterInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Srv\SourceChapterResponse\ChapterInfo::class);
        $this->chapterInfo = $arr;

        return $this;
    }

}

