<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

if (false) {
    /**
     * This class is deprecated. Use Srv\SourceChapterResponse\ChapterInfo instead.
     * @deprecated
     */
    class SourceChapterResponse_ChapterInfo {}
}
class_exists(SourceChapterResponse\ChapterInfo::class);
@trigger_error('Srv\SourceChapterResponse_ChapterInfo is deprecated and will be removed in the next major release. Use Srv\SourceChapterResponse\ChapterInfo instead', E_USER_DEPRECATED);

