<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *获取书籍源章节信息
 *
 * Generated from protobuf message <code>srv.SourceChapterRequest</code>
 */
class SourceChapterRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .srv.SourceChapterRequest.ChapterSource chapterSource = 1;</code>
     */
    private $chapterSource;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Srv\SourceChapterRequest\ChapterSource[]|\Google\Protobuf\Internal\RepeatedField $chapterSource
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\BookService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .srv.SourceChapterRequest.ChapterSource chapterSource = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChapterSource()
    {
        return $this->chapterSource;
    }

    /**
     * Generated from protobuf field <code>repeated .srv.SourceChapterRequest.ChapterSource chapterSource = 1;</code>
     * @param \Srv\SourceChapterRequest\ChapterSource[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChapterSource($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Srv\SourceChapterRequest\ChapterSource::class);
        $this->chapterSource = $arr;

        return $this;
    }

}

