<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/BookService.protoc

namespace Srv;

if (false) {
    /**
     * This class is deprecated. Use Srv\SourceChapterRequest\ChapterSource instead.
     * @deprecated
     */
    class SourceChapterRequest_ChapterSource {}
}
class_exists(SourceChapterRequest\ChapterSource::class);
@trigger_error('Srv\SourceChapterRequest_ChapterSource is deprecated and will be removed in the next major release. Use Srv\SourceChapterRequest\ChapterSource instead', E_USER_DEPRECATED);

