<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/ParserService.protoc

namespace Srv\ChapterResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>srv.ChapterResponse.Chapter</code>
 */
class Chapter extends \Google\Protobuf\Internal\Message
{
    /**
     *章节名
     *
     * Generated from protobuf field <code>string title = 1;</code>
     */
    private $title = '';
    /**
     *章节索引
     *
     * Generated from protobuf field <code>int32 index = 2;</code>
     */
    private $index = 0;
    /**
     *内容链接
     *
     * Generated from protobuf field <code>string contentsLink = 3;</code>
     */
    private $contentsLink = '';
    /**
     *源站
     *
     * Generated from protobuf field <code>string source = 4;</code>
     */
    private $source = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *          章节名
     *     @type int $index
     *          章节索引
     *     @type string $contentsLink
     *          内容链接
     *     @type string $source
     *          源站
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protoc\ParserService::initOnce();
        parent::__construct($data);
    }

    /**
     *章节名
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     *章节名
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     *章节索引
     *
     * Generated from protobuf field <code>int32 index = 2;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     *章节索引
     *
     * Generated from protobuf field <code>int32 index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;

        return $this;
    }

    /**
     *内容链接
     *
     * Generated from protobuf field <code>string contentsLink = 3;</code>
     * @return string
     */
    public function getContentsLink()
    {
        return $this->contentsLink;
    }

    /**
     *内容链接
     *
     * Generated from protobuf field <code>string contentsLink = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContentsLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->contentsLink = $var;

        return $this;
    }

    /**
     *源站
     *
     * Generated from protobuf field <code>string source = 4;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     *源站
     *
     * Generated from protobuf field <code>string source = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Chapter::class, \Srv\ChapterResponse_Chapter::class);

